name: check_update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_update:
    name: Check updates on https://tools.ietf.org/wg/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - id: update_json
        run: |
          bundle exec bin/wg2json.rb > lib/metanorma/ietf/data/workgroup.json


      - if: ${{ !steps.checkTag.outputs.exists }}
        run: |
          gem bump --version patch --tag --push
          git tag ${{ env.GNS_VERSION }}
          git push origin master --tags

      - name: publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{secrets.METANORMA_CI_RUBYGEMS_API_KEY}}
        run: |
          gem install gem-release
          envsubst << 'EOF' > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          gem release
